export const HTTP_100_CONTINUE = 'HTTP_100_CONTINUE'

export const HTTP_101_SWITCHING_PROTOCOLS = 'HTTP_101_SWITCHING_PROTOCOLS'

export const HTTP_102_PROCESSING = 'HTTP_102_PROCESSING'

export const HTTP_200_OK = 'HTTP_200_OK'

export const HTTP_201_CREATED = 'HTTP_201_CREATED'

export const HTTP_202_ACCEPTED = 'HTTP_202_ACCEPTED'

export const HTTP_203_NON_AUTHORITATIVE_INFORMATION = 'HTTP_203_NON_AUTHORITATIVE_INFORMATION'

export const HTTP_204_NO_CONTENT = 'HTTP_204_NO_CONTENT'

export const HTTP_205_RESET_CONTENT = 'HTTP_205_RESET_CONTENT'

export const HTTP_206_PARTIAL_CONTENT = 'HTTP_206_PARTIAL_CONTENT'

export const HTTP_207_MULTI_STATUS = 'HTTP_207_MULTI_STATUS'

export const HTTP_300_MULTIPLE_CHOICES = 'HTTP_300_MULTIPLE_CHOICES'

export const HTTP_301_MOVED_PERMANENTLY = 'HTTP_301_MOVED_PERMANENTLY'

export const HTTP_302_MOVED_TEMPORARILY = 'HTTP_302_MOVED_TEMPORARILY'

export const HTTP_303_SEE_OTHER = 'HTTP_303_SEE_OTHER'

export const HTTP_304_NOT_MODIFIED = 'HTTP_304_NOT_MODIFIED'

export const HTTP_305_USE_PROXY = 'HTTP_305_USE_PROXY'

export const HTTP_307_TEMPORARY_REDIRECT = 'HTTP_307_TEMPORARY_REDIRECT'

export const HTTP_308_PERMANENT_REDIRECT = 'HTTP_308_PERMANENT_REDIRECT'

export const HTTP_400_BAD_REQUEST = 'HTTP_400_BAD_REQUEST'

export const HTTP_401_UNAUTHORIZED = 'HTTP_401_UNAUTHORIZED'

export const HTTP_402_PAYMENT_REQUIRED = 'HTTP_402_PAYMENT_REQUIRED'

export const HTTP_403_FORBIDDEN = 'HTTP_403_FORBIDDEN'

export const HTTP_404_NOT_FOUND = 'HTTP_404_NOT_FOUND'

export const HTTP_405_METHOD_NOT_ALLOWED = 'HTTP_405_METHOD_NOT_ALLOWED'

export const HTTP_406_NOT_ACCEPTABLE = 'HTTP_406_NOT_ACCEPTABLE'

export const HTTP_407_PROXY_AUTHENTICATION_REQUIRED = 'HTTP_407_PROXY_AUTHENTICATION_REQUIRED'

export const HTTP_408_REQUEST_TIMEOUT = 'HTTP_408_REQUEST_TIMEOUT'

export const HTTP_409_CONFLICT = 'HTTP_409_CONFLICT'

export const HTTP_410_GONE = 'HTTP_410_GONE'

export const HTTP_411_LENGTH_REQUIRED = 'HTTP_411_LENGTH_REQUIRED'

export const HTTP_412_PRECONDITION_FAILED = 'HTTP_412_PRECONDITION_FAILED'

export const HTTP_413_REQUEST_TOO_LONG = 'HTTP_413_REQUEST_TOO_LONG'

export const HTTP_414_REQUEST_URI_TOO_LONG = 'HTTP_414_REQUEST_URI_TOO_LONG'

export const HTTP_415_UNSUPPORTED_MEDIA_TYPE = 'HTTP_415_UNSUPPORTED_MEDIA_TYPE'

export const HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE = 'HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE'

export const HTTP_417_EXPECTATION_FAILED = 'HTTP_417_EXPECTATION_FAILED'

export const HTTP_418_IM_A_TEAPOT = 'HTTP_418_IM_A_TEAPOT'

export const HTTP_419_INSUFFICIENT_SPACE_ON_RESOURCE = 'HTTP_419_INSUFFICIENT_SPACE_ON_RESOURCE'

export const HTTP_420_METHOD_FAILURE = 'HTTP_420_METHOD_FAILURE'

export const HTTP_421_MISDIRECTED_REQUEST = 'HTTP_421_MISDIRECTED_REQUEST'

export const HTTP_422_UNPROCESSABLE_ENTITY = 'HTTP_422_UNPROCESSABLE_ENTITY'

export const HTTP_423_LOCKED = 'HTTP_423_LOCKED'

export const HTTP_424_FAILED_DEPENDENCY = 'HTTP_424_FAILED_DEPENDENCY'

export const HTTP_428_PRECONDITION_REQUIRED = 'HTTP_428_PRECONDITION_REQUIRED'

export const HTTP_429_TOO_MANY_REQUESTS = 'HTTP_429_TOO_MANY_REQUESTS'

export const HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE = 'HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE'

export const HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS = 'HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS'

export const HTTP_500_INTERNAL_SERVER_ERROR = 'HTTP_500_INTERNAL_SERVER_ERROR'

export const HTTP_501_NOT_IMPLEMENTED = 'HTTP_501_NOT_IMPLEMENTED'

export const HTTP_502_BAD_GATEWAY = 'HTTP_502_BAD_GATEWAY'

export const HTTP_503_SERVICE_UNAVAILABLE = 'HTTP_503_SERVICE_UNAVAILABLE'

export const HTTP_504_GATEWAY_TIMEOUT = 'HTTP_504_GATEWAY_TIMEOUT'

export const HTTP_505_HTTP_VERSION_NOT_SUPPORTED = 'HTTP_505_HTTP_VERSION_NOT_SUPPORTED'

export const HTTP_507_INSUFFICIENT_STORAGE = 'HTTP_507_INSUFFICIENT_STORAGE'

export const HTTP_511_NETWORK_AUTHENTICATION_REQUIRED = 'HTTP_511_NETWORK_AUTHENTICATION_REQUIRED'

export const HTTPStatusCodes = {
  HTTP_100_CONTINUE,
  HTTP_101_SWITCHING_PROTOCOLS,
  HTTP_102_PROCESSING,
  HTTP_200_OK,
  HTTP_201_CREATED,
  HTTP_202_ACCEPTED,
  HTTP_203_NON_AUTHORITATIVE_INFORMATION,
  HTTP_204_NO_CONTENT,
  HTTP_205_RESET_CONTENT,
  HTTP_206_PARTIAL_CONTENT,
  HTTP_207_MULTI_STATUS,
  HTTP_300_MULTIPLE_CHOICES,
  HTTP_301_MOVED_PERMANENTLY,
  HTTP_302_MOVED_TEMPORARILY,
  HTTP_303_SEE_OTHER,
  HTTP_304_NOT_MODIFIED,
  HTTP_305_USE_PROXY,
  HTTP_307_TEMPORARY_REDIRECT,
  HTTP_308_PERMANENT_REDIRECT,
  HTTP_400_BAD_REQUEST,
  HTTP_401_UNAUTHORIZED,
  HTTP_402_PAYMENT_REQUIRED,
  HTTP_403_FORBIDDEN,
  HTTP_404_NOT_FOUND,
  HTTP_405_METHOD_NOT_ALLOWED,
  HTTP_406_NOT_ACCEPTABLE,
  HTTP_407_PROXY_AUTHENTICATION_REQUIRED,
  HTTP_408_REQUEST_TIMEOUT,
  HTTP_409_CONFLICT,
  HTTP_410_GONE,
  HTTP_411_LENGTH_REQUIRED,
  HTTP_412_PRECONDITION_FAILED,
  HTTP_413_REQUEST_TOO_LONG,
  HTTP_414_REQUEST_URI_TOO_LONG,
  HTTP_415_UNSUPPORTED_MEDIA_TYPE,
  HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE,
  HTTP_417_EXPECTATION_FAILED,
  HTTP_418_IM_A_TEAPOT,
  HTTP_419_INSUFFICIENT_SPACE_ON_RESOURCE,
  HTTP_420_METHOD_FAILURE,
  HTTP_421_MISDIRECTED_REQUEST,
  HTTP_422_UNPROCESSABLE_ENTITY,
  HTTP_423_LOCKED,
  HTTP_424_FAILED_DEPENDENCY,
  HTTP_428_PRECONDITION_REQUIRED,
  HTTP_429_TOO_MANY_REQUESTS,
  HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE,
  HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS,
  HTTP_500_INTERNAL_SERVER_ERROR,
  HTTP_501_NOT_IMPLEMENTED,
  HTTP_502_BAD_GATEWAY,
  HTTP_503_SERVICE_UNAVAILABLE,
  HTTP_504_GATEWAY_TIMEOUT,
  HTTP_505_HTTP_VERSION_NOT_SUPPORTED,
  HTTP_507_INSUFFICIENT_STORAGE,
  HTTP_511_NETWORK_AUTHENTICATION_REQUIRED,
}

export function getHTTPStatusByCode(code: string | number | null | undefined) {
  return Object.keys(HTTPStatusCodes).find((key) => key.includes(`${code}`))
}
